# Generated by Django 3.2.7 on 2021-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('payment', models.BooleanField(default=False)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
