# Generated by Django 3.2.7 on 2021-09-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
